USE master
GO
IF EXISTS(SELECT NAME FROM SYSDATABASES WHERE NAME='DB1')
	DROP DATABASE DB1
CREATE DATABASE DB1
go
USE DB1
GO

CREATE TABLE MATHANG(
	MSMH	CHAR(10)		NOT NULL PRIMARY KEY,
	TENMH	NVARCHAR(50)	NULL,
	DONGIA	FLOAT			NULL,
	DVT		NCHAR(10)		NULL,
	
);

CREATE TABLE CT_HOADON(
	MSHD	CHAR(10)	NOT NULL,
	MSMH	CHAR(10)	NOT NULL,
	SOLUONG	INT			NULL,
	CONSTRAINT	PK_CT_HOADON PRIMARY KEY(MSHD ,MSMH)
);

CREATE TABLE KHACHHANG(
	MSKH		CHAR(10)		NOT NULL,
	TENKH		NVARCHAR(50)	NULL,
	DIACHI		NVARCHAR(50)	NULL,
	DIENTHOAI	NVARCHAR(50)	NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MSKH)
);

CREATE TABLE HOADON(
	MSHD		CHAR(10)		NOT NULL,
	NGAYHD		DATETIME		NULL,
	MSKH		CHAR(10)		NOT NULL,
	MSNV		CHAR(10)		NOT NULL
	CONSTRAINT PK_HOADON	PRIMARY KEY(MSHD)
);

CREATE TABLE NHANVIEN(
	MSNV		CHAR(10)		NOT NULL,
	TENNV		NVARCHAR(50)	NULL,
	DIACHI		NVARCHAR(50)	NULL,
	CMND		CHAR(15)		NOT NULL,
	DIENTHOAI	CHAR(12)		NULL,
	NGAYSINH	DATETIME		NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MSNV)
);


ALTER TABLE HOADON
	ADD	CONSTRAINT FK_HOADON_NHANVIEN	FOREIGN KEY (MSNV) REFERENCES NHANVIEN(MSNV),
		CONSTRAINT FK_HOADON_KHACHHANG	FOREIGN KEY(MSKH)	REFERENCES KHACHHANG(MSKH)

ALTER TABLE CT_HOADON
	ADD	CONSTRAINT FK_CTHOADON_MATHANG FOREIGN KEY (MSMH) REFERENCES MATHANG(MSMH),
		CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY(MSHD)	REFERENCES HOADON(MSHD)

ALTER TABLE CT_HOADON
		DROP CONSTRAINT FK_CTHOADON_HOADON
ALTER TABLE CT_HOADON
		DROP CONSTRAINT FK_CTHOADON_MATHANG

SELECT * FROM NHANVIEN
SELECT * FROM HOADON
SELECT * FROM CT_HOADON
SELECT * FROM MATHANG
SELECT * FROM KHACHHANG
